create table difficulties (id bigserial not null, name varchar(255), points_for_task integer, required_points integer, primary key (id));
create table difficulties_tasks (difficulty_kyu_id bigint not null, tasks_id bigint not null);
create table hint (id bigserial not null, hint varchar(255), task_id bigint, primary key (id));
create table hint_received_users (hint_id bigint not null, received_users_id bigint not null);
create table images_table (id bigserial not null, name varchar(255), path varchar(255), user_id bigint, primary key (id));
create table review (id bigserial not null, rating float(53) not null, text varchar(255) not null, task_id bigint, user_id bigint, primary key (id));
create table tag (id bigserial not null, name varchar(255), primary key (id));
create table tag_tasks (tag_id bigint not null, tasks_id bigint not null);
create table task_files_table (id bigserial not null, name varchar(255), path varchar(255), task_id bigint, primary key (id));
create table tasks_table (id bigserial not null, answer varchar(255) not null, approved boolean, created_date timestamp(6), description varchar(255) not null, name varchar(255) not null, rating float(53), solved integer, added_user_id bigint, difficulty_id bigint, primary key (id));
create table tasks_table_answered_users (task_id bigint not null, answered_users_id bigint not null);
create table tasks_table_marked_users (task_id bigint not null, marked_users_id bigint not null);
create table tasks_table_reviews (task_id bigint not null, reviews_id bigint not null);
create table tasks_table_tags (task_id bigint not null, tags_id bigint not null);
create table tasks_table_task_files (task_id bigint not null, task_files_id bigint not null);
create table users_table (id bigserial not null, banned boolean, email varchar(255), email_verified boolean, password varchar(255), points integer, rank varchar(255), recovery_code varchar(255), role smallint check (role between 0 and 1), username varchar(255), verification_code varchar(255), image_id bigint, primary key (id));
create table users_table_created_tasks (user_id bigint not null, created_tasks_id bigint not null);
create table users_table_favorites (user_id bigint not null, favorites_id bigint not null);
create table users_table_reviews (user_id bigint not null, reviews_id bigint not null);
create table users_table_solved_tasks (user_id bigint not null, solved_tasks_id bigint not null);
create table users_table_used_hints (user_id bigint not null, used_hints_id bigint not null);
alter table if exists difficulties_tasks drop constraint if exists UK_bwd8k8fnfp5mq93ktbn3exi8p;
alter table if exists difficulties_tasks add constraint UK_bwd8k8fnfp5mq93ktbn3exi8p unique (tasks_id);
alter table if exists images_table drop constraint if exists UK_jkdt21gxgrldoirwjmsrih51e;
alter table if exists images_table add constraint UK_jkdt21gxgrldoirwjmsrih51e unique (user_id);
alter table if exists tasks_table_reviews drop constraint if exists UK_6og21yor4x1w5lvxrwh8b5oeb;
alter table if exists tasks_table_reviews add constraint UK_6og21yor4x1w5lvxrwh8b5oeb unique (reviews_id);
alter table if exists tasks_table_task_files drop constraint if exists UK_rhud8yioyvtdun9u7wkm74j8y;
alter table if exists tasks_table_task_files add constraint UK_rhud8yioyvtdun9u7wkm74j8y unique (task_files_id);
alter table if exists users_table drop constraint if exists UK_iyi7boyg9yfmw5p12q53hlbl8;
alter table if exists users_table add constraint UK_iyi7boyg9yfmw5p12q53hlbl8 unique (image_id);
alter table if exists users_table_created_tasks drop constraint if exists UK_dxpkyg7b3k56xol2mbqjx3mjw;
alter table if exists users_table_created_tasks add constraint UK_dxpkyg7b3k56xol2mbqjx3mjw unique (created_tasks_id);
alter table if exists users_table_reviews drop constraint if exists UK_nl6lo9eh14m0qgx5ncenbtaak;
alter table if exists users_table_reviews add constraint UK_nl6lo9eh14m0qgx5ncenbtaak unique (reviews_id);
alter table if exists difficulties_tasks add constraint FKpmgwn8t88rn3hf4kroocqtvgk foreign key (tasks_id) references tasks_table;
alter table if exists difficulties_tasks add constraint FK4sci85ynrsfmwe1fwtd58jmua foreign key (difficulty_kyu_id) references difficulties;
alter table if exists hint add constraint FKqqyi5vgpouj4atoqe9yvherwg foreign key (task_id) references tasks_table;
alter table if exists hint_received_users add constraint FK4ojjt22twwcjaood64h1fmeh3 foreign key (received_users_id) references users_table;
alter table if exists hint_received_users add constraint FKl3ioeq5j7kv0h6ayk85pvnwk0 foreign key (hint_id) references hint;
alter table if exists images_table add constraint FKdcxv9mg2kcapgy6fbj922s3kv foreign key (user_id) references users_table;
alter table if exists review add constraint FK345x252v40ndetxvn0uvkevnu foreign key (task_id) references tasks_table;
alter table if exists review add constraint FKi4tyego8mhfnay51uddh99cnl foreign key (user_id) references users_table;
alter table if exists tag_tasks add constraint FKgsc3u603ub18jen6birjmsfqs foreign key (tasks_id) references tasks_table;
alter table if exists tag_tasks add constraint FK1vt1ia4bes68crus96mtj172 foreign key (tag_id) references tag;
alter table if exists task_files_table add constraint FKfmydn96858yapj3bbynnud1h0 foreign key (task_id) references tasks_table;
alter table if exists tasks_table add constraint FK3oew3qw32vlg0kxeim7towydw foreign key (added_user_id) references users_table;
alter table if exists tasks_table add constraint FKb7rkhuu4kflvi4p8de079tujf foreign key (difficulty_id) references difficulties;
alter table if exists tasks_table_answered_users add constraint FK2qu0jgfbllpl90dwyt8gx5dwv foreign key (answered_users_id) references users_table;
alter table if exists tasks_table_answered_users add constraint FK46gqwxlx9j424aw496vvt84h5 foreign key (task_id) references tasks_table;
alter table if exists tasks_table_marked_users add constraint FKd6cmdtnsulixlovlehy7kiw37 foreign key (marked_users_id) references users_table;
alter table if exists tasks_table_marked_users add constraint FKto4960touh4j7up986ttc7sqe foreign key (task_id) references tasks_table;
alter table if exists tasks_table_reviews add constraint FKd27tjrr9o1oh2ocejmteuoybx foreign key (reviews_id) references review;
alter table if exists tasks_table_reviews add constraint FK67w9y9h9ncr8ut7k4odtscb7g foreign key (task_id) references tasks_table;
alter table if exists tasks_table_tags add constraint FKgbvshmnlcubakwqakyecnm2q9 foreign key (tags_id) references tag;
alter table if exists tasks_table_tags add constraint FKdg7a5ai38y4ucy3dabed49lkr foreign key (task_id) references tasks_table;
alter table if exists tasks_table_task_files add constraint FKmhpj7enqi9q3322nry04pkfi6 foreign key (task_files_id) references task_files_table;
alter table if exists tasks_table_task_files add constraint FKfpr7lkd4nr90583p3ne4qbo43 foreign key (task_id) references tasks_table;
alter table if exists users_table add constraint FKdfl70mf6ioh9v261m6s628ga1 foreign key (image_id) references images_table;
alter table if exists users_table_created_tasks add constraint FKab2o65i8eebo2a2k7vj1inp9o foreign key (created_tasks_id) references tasks_table;
alter table if exists users_table_created_tasks add constraint FK25tppey5u1f2ijhpvtn3j108p foreign key (user_id) references users_table;
alter table if exists users_table_favorites add constraint FK24ok1ndik3o75ufnv2c7nxto4 foreign key (favorites_id) references tasks_table;
alter table if exists users_table_favorites add constraint FKe0fhlhkxelpfu6ys2lbwa3cm foreign key (user_id) references users_table;
alter table if exists users_table_reviews add constraint FKorp6bx5v3q2axeadog16og1uo foreign key (reviews_id) references review;
alter table if exists users_table_reviews add constraint FKckppwb46onpglbcgkblly4vjv foreign key (user_id) references users_table;
alter table if exists users_table_solved_tasks add constraint FKiujycrdstrnv8ysjwcunq0c6f foreign key (solved_tasks_id) references tasks_table;
alter table if exists users_table_solved_tasks add constraint FK43fjb9yweh2kg3j43khi38xcs foreign key (user_id) references users_table;
alter table if exists users_table_used_hints add constraint FKru7ahh286vs0dxec18632ykwy foreign key (used_hints_id) references hint;
alter table if exists users_table_used_hints add constraint FK9nr7m2phg65ruh3hvftsve3c2 foreign key (user_id) references users_table
